app:
  name: "price_app"
  environment: "local"
  version: "1.0.0"
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    file: "price_app.log"
    format: "[%(asctime)s] [%(levelname)-8s] [%(name)-20s] [%(filename)s:%(lineno)d] %(message)s"

connections:
  - id: primary_db
    type: database
    enabled: true
    config_file: database.yaml
  
  - id: primary_celery
    type: celery
    enabled: true
    config_file: celery.yaml
  
  - id: primary_dagster
    type: dagster
    enabled: true
    config_file: dagster.yaml

  - id: secondary_db
    type: database
    enabled: false
    config_file: database_secondary.yaml
