database:
  connection_string: "mongodb+srv://grepx_mongo_user:Singapore%40123@grepx.f0vzhpn.mongodb.net/stock_analysis_demo?appName=grepx"
  pool_size: 10
  min_pool_size: 2
  max_pool_size: 50
  timeout: 5000
  retry_writes: true
  w: "majority"

backends:
  mongodb:
    enabled: true
    connection_string: "mongodb+srv://grepx_mongo_user:Singapore%40123@grepx.f0vzhpn.mongodb.net/stock_analysis_demo?appName=grepx"
    databases_to_delete:
      - futures_analysis
      - stocks_analysis
      - indices_analysis
  sqlite:
    enabled: false  # ← Won't run if false
    connection_string: "sqlite:///analytics.db"
    tables_to_delete: null
  postgresql:
    enabled: false  # ← Won't run if false
    connection_string: "postgresql://postgres:postgres@localhost:5432/analytics"
    tables_to_delete: null
